name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cmake .
    - run: make stim
    - run: echo -e "H 0 \n CNOT 0 1 \n M 0 1" | out/stim
  benchmark_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: cmake .
      - run: MSBuild.exe stim_benchmark.vcxproj /p:Configuration=Release /p:OutDir=msbuild_out /p:O=2
      - run: msbuild_out/stim_benchmark.exe
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        simd_width: [64, 128, 256]
    steps:
    - uses: actions/checkout@v1
    - run: cmake . -DSIMD_WIDTH=${{ matrix.simd_width }}
    - run: make stim_benchmark
    - run: out/stim_benchmark
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        simd_width: [64, 128, 256]
    steps:
    - uses: actions/checkout@v1
    - run: |
        cd ..
        git clone https://github.com/google/googletest.git -b release-1.10.0
        mkdir googletest/build && cd googletest/build
        cmake .. -DBUILD_GMOCK=OFF
        make
        sudo make install
    - run: cmake . -DSIMD_WIDTH=${{ matrix.simd_width }}
    - run: make stim_test
    - run: out/stim_test
